---
title: "Mini-Project 2"
author: "Team Hedgehog!"
date: "2/8/2021"
output:
  html_document:
    theme: journal
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo = TRUE
)
library(tidyverse)
library(mosaic)
library(dae)
```

```{r}

## M -- taking in raw data, this is updated as of feb 10th at 4:30 pm ish

raw_data <- read_csv("./raw_data.csv")
```

```{r}

## M - Cleaning data part

cleaned_data <- raw_data %>%
  filter(Consent == "Yes, I consent" & Age == "Yes, I am 18 or older") %>%
  select(Happiness1_1, `Animal-Preference`, Happiness2_1, animal) %>%
  rename(preferred_animal = `Animal-Preference`,
         trial_1 = Happiness1_1,
         trial_2 = Happiness2_1) %>%
  mutate(subject_id = as.factor(row_number())) %>% 
  na.omit() %>%
# syntax from https://tidyr.tidyverse.org/reference/pivot_longer.html
  pivot_longer(cols = c(trial_1, trial_2), names_to = "trial", values_to = "happiness") %>%
  mutate(happiness = as.numeric(happiness))
```

```{r, eval = FALSE}

## M - saving clean data for submission purposes

write.csv(x = cleaned_data, file = "cleaned_mp2.csv", sep = ",")
```


## Working with within-subjects var -- trial would be the within-subjects variable here

```{r}
## K - tally responses in each group
tally(~ animal|trial, data = cleaned_data)
tally(~ preferred_animal|trial, data = cleaned_data)
tally(~ animal|preferred_animal, data = cleaned_data) # these #s are doubled
# looks like we have a lot more cat-lovers
```



```{r}

## M - SDs in animal/preferred animal groups; SDs in trial/animal/preferred animal groups do in fact meet the same standard deviation assumption

cleaned_data %>%
  group_by(animal, preferred_animal) %>%
  summarize(
    mean = mean(happiness),
    sd = sd(happiness)
  )

## check within too just to be sure

cleaned_data %>%
  group_by(trial) %>%
  summarize(
    mean = mean(happiness),
    sd = sd(happiness)
  )
```

same sd assumption met

```{r}
## M - basic boxplot with within-subjects var, with data that does not violate assumptions

ggplot(cleaned_data, aes(x = trial, y = happiness, color = preferred_animal)) +
  geom_boxplot()

ggplot(cleaned_data, aes(x = trial, y = happiness, color = animal)) +
  geom_boxplot()
```

```{r}
## Sarah - Basic Boxplot for Trial

ggplot(cleaned_data, aes(x = trial, 
                         y = happiness)) +
  geom_boxplot(fill = "seagreen3",
               color = "grey30") +
  labs(title = "Cute Animals and Happiness", 
       x = "Measurement Timeslot", 
       y = "Level of Happiness") +
  scale_x_discrete(labels = c('Before',
                              'After')) +
  scale_y_continuous(labels = c('0',
                                '2.5',
                                '5',
                                '7.5',
                                '10'))
```

```{r}
# S - Boxplot 1
ggplot(cleaned_data, aes(x = animal, 
                         y = happiness, 
                         color = preferred_animal)) +
  geom_boxplot() +
  labs(title = "Happiness by Animal Presented \nand Animal Preference", 
       x = "Animal Presented", 
       y = "Level of Happiness",
       color = "Animal Preference") +
  scale_x_discrete(labels = c('Cat',
                              'Hedgehog')) +
  scale_y_continuous(labels = c('0',
                                '2.5',
                                '5',
                                '7.5',
                                '10')) +
  scale_color_manual(values=c("seagreen3",
                             "grey30"))
```

```{r}
# S - Boxplot 2
ggplot(cleaned_data, aes(x = trial, 
                         y = happiness, 
                         color = preferred_animal)) +
  geom_boxplot() +
  labs(title = "Happiness by Time Measurement \nand Animal Preference", 
       x = "Time Measurement", 
       y = "Level of Happiness",
       color = "Animal Preference") +
  scale_x_discrete(labels = c('Before',
                              'After')) +
  scale_y_continuous(labels = c('0',
                                '2.5',
                                '5',
                                '7.5',
                                '10')) +
  scale_color_manual(values=c("seagreen3",
                             "grey30"))
```

```{r}
# S - Boxplot 3
ggplot(cleaned_data, aes(x = trial, 
                         y = happiness, 
                         color = animal)) +
  geom_boxplot() +
  labs(title = "Happiness by Time Measurement \nand Animal Presented", 
       x = "Time Measurement", 
       y = "Level of Happiness",
       color = "Animal Presented") +
  scale_x_discrete(labels = c('Before',
                              'After')) +
  scale_y_continuous(labels = c('0',
                                '2.5',
                                '5',
                                '7.5',
                                '10')) +
  scale_color_manual(values=c("seagreen3",
                             "grey30"))
```

```{r}
# S - Boxplot 4 w/Facet
ggplot(cleaned_data, aes(x = trial, 
                         y = happiness, 
                         color = preferred_animal)) +
  geom_boxplot() +
  facet_wrap(~animal,
             labeller = labeller(animal = c("cat" = "Cat Photo",
                                            "hedgehog" = "Hedgehog Photo"))) +
  labs(title = "Happiness by Animal Presented, \nTime Measurement, \nand Animal Preference", 
       x = "Time Measurement", 
       y = "Level of Happiness",
       color = "Animal \nPreference") +
  scale_x_discrete(labels = c('Before',
                              'After')) +
  scale_y_continuous(labels = c('0',
                                '2.5',
                                '5',
                                '7.5',
                                '10')) +
  scale_color_manual(values=c("seagreen3",
                             "grey30"))
```


```{r}
## Within-subjects scatterplot
for_scatterplot <- cleaned_data %>%
  pivot_wider(names_from = trial, values_from = happiness)

ggplot(data = for_scatterplot, aes(x = trial_1, y = trial_2)) +
    geom_point() +
  scale_x_continuous("Happiness Before Image") +
  scale_y_continuous("Happiness After Image")
```


constant effects, additive assumptions met
maybe ANOVA

```{r}
# ANOVA
mod <- aov(happiness ~ preferred_animal*animal*trial + Error(subject_id) + preferred_animal*animal, data = cleaned_data)

summary(mod)

# yay, we made people happy!
```


```{r}
# M
cleaned_data <- cleaned_data %>%
  mutate(residuals = residuals(mod),
         fitted = fitted(mod))

ggplot(cleaned_data, aes(x = fitted, y = residuals)) +
  geom_point() +
  geom_hline(yintercept = 0, color = "red")


ggplot(cleaned_data, aes(x = residuals)) +
  geom_histogram(binwidth = .25)
```


## effect sizes

Overall variance explained by factor of interest: eta^2

$$\eta^2 = \frac{MS_{treatment}}{MS_{total}}$$
```{r}
# K
# just do trial
eta_squared <- 7.001 / 58.919

eta_squared
# MSTotal is sum of all MSs
# 0.1188241
# how to interpret this?
```


## confidence intervals

alpha = 0.05 level

```{r}
# K
# confidence interval
# compare trials (within-blocks)
# happiness 1 vs happiness 2
stats <- favstats(happiness ~ trial, data = cleaned_data)[,c(1,7,9)]
# diff of means
diff <- stats[2,2] - stats[1,2]
# use counts in leverage
n1 <- stats[2, 3]
n2 <- stats[1, 3]
leverage <- sqrt((1/n1)+1/n2)
# within-blocks error is MS_Res - fill by hand for simplicity
MSError <- 0.267
SE <- leverage * MSError

# df from error term
df <- 125
t_star <- qt(0.95, df, lower.tail = TRUE)

# confidence interval
lower <- diff - SE * t_star
upper <- diff + SE * t_star

lower
upper

# we are 95% confident that the difference between trial 1 and trial 2 is between lower and upper (-0.385, -0.274)
```

Other confidence intervals, just to show we know how :)

```{r}
# K
# confidence interval
# compare cats and hedgehogs for trial 2
stats <- favstats(happiness ~ trial + animal, data = cleaned_data)[,c(1,7,9)]
# diff of means
diff <- stats[2,2] - stats[4,2]
# use counts in leverage
n1 <- stats[2, 3]
n2 <- stats[4, 3]
leverage <- sqrt((1/n1)+1/n2)

# MSPooled
# sum of error SSs / sum of error dfs
SSRes <- 33.32
SSBlocks <- 1092.0
dfRes <- 125
dfBlocks <- 125
MSError <- (SSBlocks + SSRes) / (dfBlocks + dfRes)
SE <- leverage * MSError

# df is (sum of error SSs)^2/sum of (sS^2/df)
df <- (SSBlocks + SSRes)^2 / (((SSBlocks^2)/dfBlocks) + ((SSRes^2)/dfRes))
t_star <- qt(0.95, df, lower.tail = TRUE)

# confidence interval
lower <- diff - SE * t_star
upper <- diff + SE * t_star

lower
upper

# we are 95% confident that the difference between animals for trial 2 is between lower and upper (-1.059, 1.567)
# this contains 0!!!
```

```{r}
# K
# confidence interval
# compare animal preferences for trial 2
stats <- favstats(happiness ~ trial + preferred_animal, data = cleaned_data)[,c(1,7,9)]
# diff of means
diff <- stats[2,2] - stats[4,2]
# use counts in leverage
n1 <- stats[2, 3]
n2 <- stats[4, 3]
leverage <- sqrt((1/n1)+1/n2)

# MSPooled
# sum of error SSs / sum of error dfs
SSRes <- 33.32
SSBlocks <- 1092.0
dfRes <- 125
dfBlocks <- 125
MSError <- (SSBlocks + SSRes) / (dfBlocks + dfRes)
SE <- leverage * MSError

# df is (sum of error SSs)^2/sum of (sS^2/df)
df <- (SSBlocks + SSRes)^2 / (((SSBlocks^2)/dfBlocks) + ((SSRes^2)/dfRes))
t_star <- qt(0.95, df, lower.tail = TRUE)

# confidence interval
lower <- diff - SE * t_star
upper <- diff + SE * t_star

lower
upper

# we are 95% confident that the difference between animals for trial 2 is between lower and upper (-2.035, 0.974)
# this contains 0!!!
```
